In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
df1 = pd.read_excel("../main_data/data_classic.xlsx")
df1.head()

,Название игры,Ресторан,Дата,День недели,Номер пакета,Название команды,Последний раунд,Всего баллов,Место
0,"Квиз, плиз! SPB #174",Street Food Bar №1,26.06.2019,Ср,1,Геннна и Ко,16.0,51.0,1
1,"Квиз, плиз! SPB #174",Street Food Bar №1,26.06.2019,Ср,1,Отвечает Борис Бурда,13.0,46.0,2
2,"Квиз, плиз! SPB #174",Street Food Bar №1,26.06.2019,Ср,1,N веселых гусей,16.0,45.0,3
3,"Квиз, плиз! SPB #174",Street Food Bar №1,26.06.2019,Ср,1,In vino veritas,11.0,43.0,4
4,"Квиз, плиз! SPB #174",Street Food Bar №1,26.06.2019,Ср,1,Полная дикость,10.0,43.0,5

In [13]:
import datetime


classic_dates = ['29.08.2024', '30.05.2024', '29.02.2024', '30.11.2023']
date_season = classic_dates[1]
date_season2 = classic_dates[2]
date_now = datetime.datetime.now().date().strftime('%d.%m.%Y')

start_date = pd.to_datetime(date_season2, format='%d.%m.%Y')
print(start_date)
end_date = pd.to_datetime(date_season, format='%d.%m.%Y')
df1['Дата'] = pd.to_datetime(df1['Дата'], format='%d.%m.%Y')
df1 = df1[(df1['Дата'] >= start_date) & (df1['Дата'] < end_date)] 
df1 = df1[df1['Название игры'].str.contains("Квиз, плиз! SPB", na=False)]
df1.head()

2024-02-29 00:00:00

,Название игры,Ресторан,Дата,День недели,Номер пакета,Название команды,Последний раунд,Всего баллов,Место
47099,"Квиз, плиз! SPB #784",ЦИНЬ,2024-02-29,Чт,2,База звуков,11.0,39.0,1
47100,"Квиз, плиз! SPB #784",ЦИНЬ,2024-02-29,Чт,2,Red Panda,10.0,39.0,2
47101,"Квиз, плиз! SPB #784",ЦИНЬ,2024-02-29,Чт,2,Без четверти лето,13.0,38.0,3
47102,"Квиз, плиз! SPB #784",ЦИНЬ,2024-02-29,Чт,2,ПохоТороМоронго,9.0,37.0,4
47103,"Квиз, плиз! SPB #784",ЦИНЬ,2024-02-29,Чт,2,ЧЕЛ,15.0,36.0,5

In [14]:
df2 = pd.read_excel("finals.xlsx")
df2['Дата'] = pd.to_datetime(df2['Дата'], format='%d.%m.%Y')
df2 = df2[(df2['Дата'] == end_date)] 
df2.head()

,Название игры,Ресторан,Дата,День недели,Номер пакета,Название команды,Всего баллов,Место
287,ОТКРЫТИЕ ЛЕТНЕГО СЕЗОНА [финал] SPB,VOKZAL 1853,2024-05-30,Чт,3,А я говорила!,53.0,1
288,ОТКРЫТИЕ ЛЕТНЕГО СЕЗОНА [финал] SPB,VOKZAL 1853,2024-05-30,Чт,3,Soviet Champagne,51.0,2
289,ОТКРЫТИЕ ЛЕТНЕГО СЕЗОНА [финал] SPB,VOKZAL 1853,2024-05-30,Чт,3,Зигзаг у Дачи,50.5,3
290,ОТКРЫТИЕ ЛЕТНЕГО СЕЗОНА [финал] SPB,VOKZAL 1853,2024-05-30,Чт,3,Васаби,50.5,4
291,ОТКРЫТИЕ ЛЕТНЕГО СЕЗОНА [финал] SPB,VOKZAL 1853,2024-05-30,Чт,3,Вещие сны Билли,49.0,5

In [15]:
new_df2 = df2.drop(['Название игры', 'Ресторан', 'Дата', 'День недели', 'Номер пакета'], axis=1)
new_df1 = df1.drop(['Название игры', 'Ресторан', 'Дата', 'День недели', 'Номер пакета', 'Последний раунд'], axis=1)

In [16]:
new_df2.head()

     Название команды  Всего баллов  Место
287     А я говорила!          53.0      1
288  Soviet Champagne          51.0      2
289     Зигзаг у Дачи          50.5      3
290            Васаби          50.5      4
291   Вещие сны Билли          49.0      5

In [17]:
df1_grouped = new_df1.groupby('Название команды').agg(
    Среднее_место=('Место', lambda x: round(x.mean(), 2)),
    Средний_балл=('Всего баллов', lambda x: round(x.mean(), 2)),
    Количество_игр=('Название команды', 'size')
).reset_index()

In [18]:
result = pd.merge(new_df2, df1_grouped, on='Название команды', how='left')
result = result.rename({'Всего баллов': 'Всего баллов в финале', 'Место': 'Место в финале', 'Среднее_место': 'Среднее место в сезоне', 'Средний_балл': 'Средний балл в сезоне', 'Количество_игр': 'Кол-во игр в сезоне'}, axis=1)
result = result[['Название команды', 'Кол-во игр в сезоне', 'Среднее место в сезоне', 'Место в финале', 'Средний балл в сезоне', 'Всего баллов в финале']]
result.head(60)

,Название команды,Кол-во игр в сезоне,Среднее место в сезоне,Место в финале,Средний балл в сезоне,Всего баллов в финале
0,А я говорила!,10.0,3.50,1,46.50,53.0
1,Soviet Champagne,4.0,2.00,2,51.75,51.0
2,Зигзаг у Дачи,6.0,2.33,3,47.50,50.5
3,Васаби,NaN,NaN,4,NaN,50.5
4,Вещие сны Билли,8.0,9.50,5,41.00,49.0
5,"Шевелись, Плотва!",7.0,9.29,6,39.71,49.0
6,Без якоря,4.0,2.75,7,54.50,48.5
7,"Давайте что-нибудь сложненькое, что знаю только я",3.0,4.33,8,49.67,48.0
8,Игътибар,5.0,6.40,9,39.60,48.0
9,Камю ин ё Кант,10.0,4.30,10,47.90,47.0
10,Теленок несмышленый губами ищет мамки вымя,14.0,4.29,11,47.29,46.5
11,Трудно плыть боком,5.0,2.00,12,47.60,45.5
12,Жизнь и грабля,5.0,3.40,13,49.00,45.5
13,Фривольные Каменщики Jr,1.0,2.00,14,57.00,44.5
14,Неоптимальный состав,3.0,4.33,15,42.33,44.0
15,Анатолий Басурман,2.0,7.00,16,37.00,43.0
16,Давайте ещё немного подумаем,5.0,4.20,17,45.60,42.5
17,Funny cucumber,3.0,4.67,18,46.67,42.0
18,Любви все плоскости покорны!,8.0,6.25,19,45.62,41.5
19,нрзб,4.0,8.25,20,41.00,41.0
20,Крем Брюллофф,6.0,9.33,21,41.00,40.5
21,Синдром Марии-Антуанетты,4.0,5.25,22,48.50,40.5
22,Дюмасброды,8.0,4.50,23,47.00,40.0
23,Опять про Бали,8.0,5.12,24,43.75,40.0
24,Во всем виноват Тиндер,6.0,6.67,25,41.33,40.0
25,Ученики Бориса,NaN,NaN,26,NaN,39.0
26,Неопознанный койот,4.0,7.75,27,34.00,39.0
27,Без Николая,5.0,10.00,28,40.60,38.5
28,Недоброе мороженое,6.0,7.33,29,36.33,38.0
29,"Двое в лодке, не считая кошки",6.0,8.83,30,41.17,38.0
30,Гравицапа,4.0,9.00,31,42.75,38.0
31,Мокрые Псы,NaN,NaN,32,NaN,38.0
32,Однозначный IQ,5.0,9.60,33,41.80,37.5
33,FullHouse!,5.0,9.00,34,44.40,37.5
34,По(НА)ехавшие,1.0,5.00,35,45.00,37.0
35,Убийство двойным экспрессо,4.0,4.50,36,43.00,36.5
36,Брейнстормеры,8.0,6.75,37,43.00,36.0
37,Неформальное Объединение Молодёжи,10.0,6.60,38,44.00,36.0
38,bikini bottom,3.0,2.33,39,46.67,35.5
39,Должно получиться!,NaN,NaN,40,NaN,35.5
40,"Истина в пиве, короче…",1.0,7.00,41,39.00,35.5
41,Арт&догс,5.0,8.60,42,37.40,35.5
42,Ай лав НИИ,2.0,5.00,43,48.50,35.5
43,Хмели сумели,4.0,17.50,44,33.00,34.5
44,Diputs era ew!,5.0,10.20,45,40.60,34.5
45,Мявчики,4.0,12.50,46,36.25,33.5
46,N веселых гусей,7.0,16.57,47,32.71,33.0
47,Mongoloid,3.0,9.33,48,37.00,31.5
48,Немоймопед,6.0,8.83,49,42.50,31.0
49,Устрицы паскуды,3.0,6.67,50,33.67,30.0
50,Вишнёвый пирог,3.0,12.00,51,35.67,29.5
51,Пролетая на гнезде кукушки,3.0,13.33,52,30.67,29.5
52,ГусьЯйцеКусь,5.0,9.20,53,39.40,29.5
53,Headless,3.0,4.67,54,41.67,28.0
54,Немирович-Данченко,14.0,10.57,55,34.86,28.0
55,Скаредные Великаны,3.0,6.67,56,44.00,27.5
56,Гедонизм и склерозъ,3.0,10.33,57,43.00,24.5
57,Ума по Лайту,5.0,17.00,58,32.80,24.5
58,Фантастические твари,3.0,25.00,59,20.67,23.5
59,Просто забей,3.0,22.67,60,33.67,17.5

In [19]:
new_df11 = df1[df1['Название команды'] == 'Фривольные Каменщики Jr']
new_df11.head(38)

,Название игры,Ресторан,Дата,День недели,Номер пакета,Название команды,Последний раунд,Всего баллов,Место
48819,"Квиз, плиз! SPB #817",VOKZAL 1853,2024-05-17,Пт,2,Фривольные Каменщики Jr,16.0,57.0,2